server:
  port: 8083
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/auction-realm

management:
  tracing:
    sampling:
      probability: 1.0
