server:
  port: 8083
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/auction-realm

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
