server:
  port: 8084
spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/auction-realm
  datasource:
    url: jdbc:postgresql://localhost:5434/notificationdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
