version: '3.8'

services:

  auction-db:
    image: postgres
    container_name: auction-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auctiondb
    volumes:
      - auction-db-data:/var/lib/postgres/data

  bid-db:
    image: postgres
    container_name: bid-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: biddb
    volumes:
      - bid-db-data:/var/lib/postgres/data

  auth-db:
    image: postgres
    container_name: auth-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloakdb
    volumes:
      - auth-db-data:/var/lib/postgres/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    depends_on:
      - auth-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth-db:5432/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
        - "8000:8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  auction-db-data:
  bid-db-data:
  auth-db-data:
  rabbitmq-data:
