version: '3.8'

services:

  auction-db:
    image: postgres
    container_name: auction-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auctiondb
    volumes:
      - auction-db-data:/var/lib/postgres/data

  bid-db:
    image: postgres
    container_name: bid-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: biddb
    volumes:
      - bid-db-data:/var/lib/postgres/data

  user-db:
    image: postgres
    container_name: user-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgres/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  auction-db-data:
  bid-db-data:
  user-db-data:
  rabbitmq-data:
