spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auction-service
          uri: http://localhost:8081
          predicates:
            - Path=/auctions, /auctions/*
        - id: bid-service
          uri: http://localhost:8082
          predicates:
            - Path=/bids, /bids/auction/*
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/register, /users/login

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret-key: test

logging:
  level:
    org.springframework.cloud.gateway: DEBUG