server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/userdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update