server:
  port: 8081
spring:
  application:
    name: auction-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/auction-realm
  datasource:
    url: jdbc:postgresql://localhost:5432/auctiondb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  tracing:
    sampling:
      probability: 1.0
