spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctions
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
