server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/auction-realm
  cloud:
    gateway:
      routes:
        - id: auction-service
          uri: http://localhost:8081
          predicates:
            - Path=/auctions, /auctions/*
        - id: bid-service
          uri: http://localhost:8082
          predicates:
            - Path=/bids, /bids/auction/*
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/token, /auth/refresh-token, /auth/logout
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG