spring:
  cloud:
    gateway:
      routes:
        - id: auction-service
          uri: http://localhost:8081
          predicates:
            - Path=/auctions, /auctions/*
        - id: bid-service
          uri: http://localhost:8082
          predicates:
            - Path=/bids, /bids/auction/*

logging:
  level:
    org.springframework.cloud.gateway: DEBUG